export const codeToMessage = (code: string) => {
  const errorMap = {
    "auth/admin-restricted-operation":
      "Hoạt động bị giới hạn cho quản trị viên",
    "auth/argument-error": "Lỗi đối số",
    "auth/app-not-authorized": "Ứng dụng chưa được ủy quyền",
    "auth/app-not-installed": "Ứng dụng chưa được cài đặt",
    "auth/captcha-check-failed": "Kiểm tra Captcha không thành công",
    "auth/code-expired": "Mã đã hết hạn",
    "auth/cordova-not-ready": "Cordova chưa sẵn sàng",
    "auth/cors-unsupported": "CORS không được hỗ trợ",
    "auth/credential-already-in-use": "Thông tin xác thực đã được sử dụng",
    "auth/custom-token-mismatch": "Mã token tùy chỉnh không khớp",
    "auth/requires-recent-login": "Yêu cầu đăng nhập gần đây",
    "auth/dependent-sdk-initialized-before-auth":
      "SDK phụ thuộc đã được khởi tạo trước khi xác thực",
    "auth/dynamic-link-not-activated": "Liên kết động chưa được kích hoạt",
    "auth/email-change-needs-verification": "Thay đổi email cần xác minh",
    "auth/email-already-in-use": "Email đã được sử dụng",
    "auth/emulator-config-failed": "Cấu hình giả lập không thành công",
    "auth/expired-action-code": "Mã hành động đã hết hạn",
    "auth/cancelled-popup-request": "Yêu cầu cửa sổ bật lên bị hủy",
    "auth/internal-error": "Lỗi nội bộ",
    "auth/invalid-api-key": "API key không hợp lệ",
    "auth/invalid-app-credential": "Thông tin xác thực ứng dụng không hợp lệ",
    "auth/invalid-app-id": "ID ứng dụng không hợp lệ",
    "auth/invalid-user-token": "Mã người dùng không hợp lệ",
    "auth/invalid-auth-event": "Sự kiện xác thực không hợp lệ",
    "auth/invalid-cert-hash": "Mã băm chứng chỉ không hợp lệ",
    "auth/invalid-verification-code": "Mã xác minh không hợp lệ",
    "auth/invalid-continue-uri": "URI tiếp tục không hợp lệ",
    "auth/invalid-cordova-configuration": "Cấu hình Cordova không hợp lệ",
    "auth/invalid-custom-token": "Mã token tùy chỉnh không hợp lệ",
    "auth/invalid-dynamic-link-domain": "Tên miền liên kết động không hợp lệ",
    "auth/invalid-email": "Email không hợp lệ",
    "auth/invalid-emulator-scheme": "Sơ đồ giả lập không hợp lệ",
    "auth/invalid-credential": "Thông tin xác thực không hợp lệ",
    "auth/invalid-message-payload": "Nội dung thông báo không hợp lệ",
    "auth/invalid-multi-factor-session": "Phiên đa yếu tố không hợp lệ",
    "auth/invalid-oauth-client-id": "ID khách hàng OAuth không hợp lệ",
    "auth/invalid-oauth-provider": "Nhà cung cấp OAuth không hợp lệ",
    "auth/invalid-action-code": "Mã hành động không hợp lệ",
    "auth/unauthorized-domain": "Tên miền không được ủy quyền",
    "auth/wrong-password": "Sai mật khẩu",
    "auth/invalid-persistence-type": "Loại lưu trữ không hợp lệ",
    "auth/invalid-phone-number": "Số điện thoại không hợp lệ",
    "auth/invalid-provider-id": "ID nhà cung cấp không hợp lệ",
    "auth/invalid-recipient-email": "Email người nhận không hợp lệ",
    "auth/invalid-sender": "Người gửi không hợp lệ",
    "auth/invalid-verification-id": "ID xác minh không hợp lệ",
    "auth/invalid-tenant-id": "ID người thuê không hợp lệ",
    "auth/multi-factor-info-not-found": "Không tìm thấy thông tin đa yếu tố",
    "auth/multi-factor-auth-required": "Yêu cầu xác thực đa yếu tố",
    "auth/missing-android-pkg-name": "Thiếu tên gói Android",
    "auth/missing-app-credential": "Thiếu thông tin xác thực ứng dụng",
    "auth/auth-domain-config-required": "Cần cấu hình tên miền xác thực",
    "auth/missing-verification-code": "Thiếu mã xác minh",
    "auth/missing-continue-uri": "Thiếu URI tiếp tục",
    "auth/missing-iframe-start": "Thiếu bắt đầu iframe",
    "auth/missing-ios-bundle-id": "Thiếu ID gói iOS",
    "auth/missing-or-invalid-nonce": "Thiếu hoặc nonce không hợp lệ",
    "auth/missing-multi-factor-info": "Thiếu thông tin đa yếu tố",
    "auth/missing-multi-factor-session": "Thiếu phiên đa yếu tố",
    "auth/missing-phone-number": "Thiếu số điện thoại",
    "auth/missing-verification-id": "Thiếu ID xác minh",
    "auth/app-deleted": "Ứng dụng đã bị xóa",
    "auth/account-exists-with-different-credential":
      "Tài khoản tồn tại với thông tin xác thực khác",
    "auth/network-request-failed": "Yêu cầu mạng thất bại",
    "auth/null-user": "Người dùng trống",
    "auth/no-auth-event": "Không có sự kiện xác thực",
    "auth/no-such-provider": "Không có nhà cung cấp nào như vậy",
    "auth/operation-not-allowed": "Hoạt động không được phép",
    "auth/operation-not-supported-in-this-environment":
      "Hoạt động không được hỗ trợ trong môi trường này",
    "auth/popup-blocked": "Cửa sổ bật lên bị chặn",
    "auth/popup-closed-by-user": "Cửa sổ bật lên bị đóng bởi người dùng",
    "auth/provider-already-linked": "Nhà cung cấp đã được liên kết",
    "auth/quota-exceeded": "Đã vượt quá hạn mức",
    "auth/redirect-cancelled-by-user": "Chuyển hướng bị hủy bởi người dùng",
    "auth/redirect-operation-pending": "Hoạt động chuyển hướng đang chờ",
    "auth/rejected-credential": "Thông tin xác thực bị từ chối",
    "auth/second-factor-already-in-use": "Yếu tố thứ hai đã được sử dụng",
    "auth/maximum-second-factor-count-exceeded":
      "Đã vượt quá số lượng yếu tố thứ hai tối đa",
    "auth/tenant-id-mismatch": "ID người thuê không khớp",
    "auth/timeout": "Hết thời gian chờ",
    "auth/user-token-expired": "Mã người dùng đã hết hạn",
    "auth/too-many-requests": "Quá nhiều yêu cầu",
    "auth/unauthorized-continue-uri": "URI tiếp tục không được ủy quyền",
    "auth/unsupported-first-factor": "Yếu tố đầu tiên không được hỗ trợ",
    "auth/unsupported-persistence-type": "Loại lưu trữ không được hỗ trợ",
    "auth/unsupported-tenant-operation":
      "Hoạt động người thuê không được hỗ trợ",
    "auth/unverified-email": "Email chưa được xác minh",
    "auth/user-cancelled": "Người dùng đã hủy",
    "auth/user-not-found": "Không tìm thấy người dùng",
    "auth/user-disabled": "Người dùng bị vô hiệu hóa",
    "auth/user-mismatch": "Người dùng không khớp",
    "auth/user-signed-out": "Người dùng đã đăng xuất",
    "auth/weak-password": "Mật khẩu yếu",
    "auth/web-storage-unsupported": "Lưu trữ web không được hỗ trợ",
    "auth/already-initialized": "Đã được khởi tạo",
    "auth/recaptcha-not-enabled": "Recaptcha chưa được kích hoạt",
    "auth/missing-recaptcha-token": "Thiếu mã Recaptcha",
    "auth/invalid-recaptcha-token": "Mã Recaptcha không hợp lệ",
    "auth/invalid-recaptcha-action": "Hành động Recaptcha không hợp lệ",
    "auth/missing-client-type": "Thiếu loại khách hàng",
    "auth/missing-recaptcha-version": "Thiếu phiên bản Recaptcha",
    "auth/invalid-recaptcha-version": "Phiên bản Recaptcha không hợp lệ",
    "auth/invalid-req-type": "Loại yêu cầu không hợp lệ",
    "auth/missing-password": "Mật khẩu không được để trống",
  };

  return errorMap[code as keyof typeof errorMap] || "Lỗi không xác định";
};
